# Site Information
description: "Ricky's Dev Blog. Themes by ahonn/hello"
keywords: "Ricky Kurniawan, Developer, Blog, Web development"
favicon: images/site_logo_static.svg
rss: /atom.xml

# Site Menu
# Need slash(/) at the end
menu:
  home: /
  # 技术: categories/technology/ 
  # 思考: categories/thinking/
  # 生活: categories/life/
  archives: archives/
  about: about/

# Site Sidebar Widget
widgets:
  - recent_post
  - tagcloud
  - categories
  # - archives
  - links

# Site Friend Links
#links:
  #yzzting: http://www.yzz1995.cn/
  #co1mugx: http://blog.co1mugx.tk/
  #leyar: https://www.ileyar.com/

analytics:
  google: UA-101602659-1

# Site Verification
verification:
  google: 0-0

comment:
  disqus: rickykurniawanlie
